#!/usr/bin/env bash

set -e

. /etc/ansible-pull-systemd.conf

TEMP="/tmp/$(uuidgen)"

runuser -l ${USER} -c "ansible-pull -U ${URL} -v -C ${CHECKOUT} -c local --private-key=${PRIVATE_KEY_FILE} --directory=${TEMP} --accept-host-key --purge ${EXTRA_ARGS}"

# There is a bug preventing purging the folder properly on become.
rm -rf ${TEMP}

systemctl disable ansible-pull-systemd.service
