#!/usr/bin/env bash

set -e

. /etc/ansible-pull-systemd.conf

TEMP=$(mktemp -d)

chown -R ${USER}:${USER} ${TEMP}

runuser -l ${USER} -c "ansible-pull -U ${URL} -v -C ${CHECKOUT} -c local --private-key=${PRIVATE_KEY_FILE} --directory=${TEMP}/git --accept-host-key ${EXTRA_ARGS}"

# There is a bug preventing purging the folder properly on become.
rm -rf ${TEMP}

systemctl disable ansible-pull-systemd.service
